# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubnetCalculator_UI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 576)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 321, 131))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_CalculatedSubnetSize = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_CalculatedSubnetSize.setEnabled(False)
        self.lineEdit_CalculatedSubnetSize.setGeometry(QtCore.QRect(160, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_CalculatedSubnetSize.setFont(font)
        self.lineEdit_CalculatedSubnetSize.setObjectName("lineEdit_CalculatedSubnetSize")
        self.lineEdit_HostsPerSubnet = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_HostsPerSubnet.setGeometry(QtCore.QRect(160, 70, 113, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_HostsPerSubnet.setFont(font)
        self.lineEdit_HostsPerSubnet.setObjectName("lineEdit_HostsPerSubnet")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_NetworkAddress = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_NetworkAddress.setGeometry(QtCore.QRect(160, 40, 151, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_NetworkAddress.setFont(font)
        self.lineEdit_NetworkAddress.setObjectName("lineEdit_NetworkAddress")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 321, 371))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.listWidgetIpRanges = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidgetIpRanges.setEnabled(True)
        self.listWidgetIpRanges.setGeometry(QtCore.QRect(10, 20, 301, 341))
        self.listWidgetIpRanges.setObjectName("listWidgetIpRanges")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(340, 20, 411, 211))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(30, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(30, 85, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(30, 116, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_DecimalOctets = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_DecimalOctets.setEnabled(False)
        self.lineEdit_DecimalOctets.setGeometry(QtCore.QRect(142, 20, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_DecimalOctets.setFont(font)
        self.lineEdit_DecimalOctets.setObjectName("lineEdit_DecimalOctets")
        self.lineEdit_DecimalAddress = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_DecimalAddress.setEnabled(False)
        self.lineEdit_DecimalAddress.setGeometry(QtCore.QRect(142, 51, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_DecimalAddress.setFont(font)
        self.lineEdit_DecimalAddress.setObjectName("lineEdit_DecimalAddress")
        self.lineEdit_BinaryOctets = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_BinaryOctets.setEnabled(False)
        self.lineEdit_BinaryOctets.setGeometry(QtCore.QRect(142, 83, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_BinaryOctets.setFont(font)
        self.lineEdit_BinaryOctets.setObjectName("lineEdit_BinaryOctets")
        self.lineEdit_HexOctects = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_HexOctects.setEnabled(False)
        self.lineEdit_HexOctects.setGeometry(QtCore.QRect(142, 114, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_HexOctects.setFont(font)
        self.lineEdit_HexOctects.setObjectName("lineEdit_HexOctects")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(340, 240, 411, 181))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(30, 30, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(29, 60, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(30, 90, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(30, 120, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(30, 150, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_NetworkClass = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_NetworkClass.setEnabled(False)
        self.lineEdit_NetworkClass.setGeometry(QtCore.QRect(160, 30, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_NetworkClass.setFont(font)
        self.lineEdit_NetworkClass.setObjectName("lineEdit_NetworkClass")
        self.lineEdit_NumIP_Addresses = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_NumIP_Addresses.setEnabled(False)
        self.lineEdit_NumIP_Addresses.setGeometry(QtCore.QRect(160, 60, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_NumIP_Addresses.setFont(font)
        self.lineEdit_NumIP_Addresses.setObjectName("lineEdit_NumIP_Addresses")
        self.lineEdit_SubnetMask = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_SubnetMask.setEnabled(False)
        self.lineEdit_SubnetMask.setGeometry(QtCore.QRect(160, 90, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_SubnetMask.setFont(font)
        self.lineEdit_SubnetMask.setObjectName("lineEdit_SubnetMask")
        self.lineEdit_BinaryMask = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_BinaryMask.setEnabled(False)
        self.lineEdit_BinaryMask.setGeometry(QtCore.QRect(160, 120, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_BinaryMask.setFont(font)
        self.lineEdit_BinaryMask.setObjectName("lineEdit_BinaryMask")
        self.lineEdit_NumOfSubnets = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_NumOfSubnets.setEnabled(False)
        self.lineEdit_NumOfSubnets.setGeometry(QtCore.QRect(160, 150, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_NumOfSubnets.setFont(font)
        self.lineEdit_NumOfSubnets.setObjectName("lineEdit_NumOfSubnets")
        self.pushButton_Calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Calculate.setGeometry(QtCore.QRect(630, 440, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Calculate.setFont(font)
        self.pushButton_Calculate.setObjectName("pushButton_Calculate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.actionSave_As.setFont(font)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionCalculate = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.actionCalculate.setFont(font)
        self.actionCalculate.setObjectName("actionCalculate")
        self.actionClear = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.actionClear.setFont(font)
        self.actionClear.setObjectName("actionClear")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionCalculate)
        self.menuTools.addAction(self.actionClear)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Subnet Calculator"))
        self.groupBox.setTitle(_translate("MainWindow", "Network Information"))
        self.label_4.setText(_translate("MainWindow", "Calculated Subnet Size:"))
        self.label_3.setText(_translate("MainWindow", "# of Hosts Per Subnet:"))
        self.label_2.setText(_translate("MainWindow", "Network Address:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "List of IP Ranges"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Address Information"))
        self.label.setText(_translate("MainWindow", "Decimal Octets:"))
        self.label_5.setText(_translate("MainWindow", "Decimal Address:"))
        self.label_6.setText(_translate("MainWindow", "Binary Octets:"))
        self.label_7.setText(_translate("MainWindow", "Hex Octects:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Netmask Information"))
        self.label_8.setText(_translate("MainWindow", "Network Class:"))
        self.label_9.setText(_translate("MainWindow", "# of IP Addresses:"))
        self.label_10.setText(_translate("MainWindow", "Subnet Mask:"))
        self.label_11.setText(_translate("MainWindow", "Binary Mask:"))
        self.label_12.setText(_translate("MainWindow", "# of Subnets:"))
        self.pushButton_Calculate.setText(_translate("MainWindow", "Calculate"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionCalculate.setText(_translate("MainWindow", "Calculate"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

